package modelo;
// Generated Apr 8, 2018 6:45:46 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Abogado generated by hbm2java
 */
@Entity
@Table(name="abogado"
    ,schema="public"
)
public class Abogado  implements java.io.Serializable {


     private BigDecimal idAbogado;
     private Usuario usuario;
     private String nombre;
     private String apellido;
     private String direccion;
     private String telefono;
     private Integer ci;
     private String ruc;
     private Set expedientes = new HashSet(0);
     private Set historials = new HashSet(0);

    public Abogado() {
    }

	
    public Abogado(BigDecimal idAbogado, String nombre, String apellido, String direccion, String telefono) {
        this.idAbogado = idAbogado;
        this.nombre = nombre;
        this.apellido = apellido;
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public Abogado(BigDecimal idAbogado, Usuario usuario, String nombre, String apellido, String direccion, String telefono, Integer ci, String ruc, Set expedientes, Set historials) {
       this.idAbogado = idAbogado;
       this.usuario = usuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.telefono = telefono;
       this.ci = ci;
       this.ruc = ruc;
       this.expedientes = expedientes;
       this.historials = historials;
    }
   
     @Id 

    
    @Column(name="id_abogado", nullable=false, precision=131089, scale=0)
    public BigDecimal getIdAbogado() {
        return this.idAbogado;
    }
    
    public void setIdAbogado(BigDecimal idAbogado) {
        this.idAbogado = idAbogado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="nombre", nullable=false, length=15)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", nullable=false, length=20)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="direccion", nullable=false, length=40)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="telefono", nullable=false, length=12)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="ci", precision=8, scale=0)
    public Integer getCi() {
        return this.ci;
    }
    
    public void setCi(Integer ci) {
        this.ci = ci;
    }

    
    @Column(name="ruc")
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="abogado")
    public Set getExpedientes() {
        return this.expedientes;
    }
    
    public void setExpedientes(Set expedientes) {
        this.expedientes = expedientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="abogado")
    public Set getHistorials() {
        return this.historials;
    }
    
    public void setHistorials(Set historials) {
        this.historials = historials;
    }




}


