package modelo;
// Generated Apr 8, 2018 6:45:46 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clase generated by hbm2java
 */
@Entity
@Table(name="clase"
    ,schema="public"
)
public class Clase  implements java.io.Serializable {


     private BigDecimal idClase;
     private String descripcion;
     private Set marcas = new HashSet(0);

    public Clase() {
    }

	
    public Clase(BigDecimal idClase, String descripcion) {
        this.idClase = idClase;
        this.descripcion = descripcion;
    }
    public Clase(BigDecimal idClase, String descripcion, Set marcas) {
       this.idClase = idClase;
       this.descripcion = descripcion;
       this.marcas = marcas;
    }
   
     @Id 

    
    @Column(name="id_clase", nullable=false, precision=131089, scale=0)
    public BigDecimal getIdClase() {
        return this.idClase;
    }
    
    public void setIdClase(BigDecimal idClase) {
        this.idClase = idClase;
    }

    
    @Column(name="descripcion", nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clase")
    public Set getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Set marcas) {
        this.marcas = marcas;
    }




}


