package modelo;
// Generated Apr 7, 2018 6:38:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Clase generated by hbm2java
 */
public class Clase  implements java.io.Serializable {


     private BigDecimal idClase;
     private String descripcion;
     private Set marcas = new HashSet(0);

    public Clase() {
    }

	
    public Clase(BigDecimal idClase, String descripcion) {
        this.idClase = idClase;
        this.descripcion = descripcion;
    }
    public Clase(BigDecimal idClase, String descripcion, Set marcas) {
       this.idClase = idClase;
       this.descripcion = descripcion;
       this.marcas = marcas;
    }
   
    public BigDecimal getIdClase() {
        return this.idClase;
    }
    
    public void setIdClase(BigDecimal idClase) {
        this.idClase = idClase;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Set marcas) {
        this.marcas = marcas;
    }




}


