package modelo;
// Generated 12-mar-2018 19:22:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Clase generated by hbm2java
 */
public class Clase  implements java.io.Serializable {


     private BigDecimal idClase;
     private String descripcion;
     private Set<Marca> marcas = new HashSet<Marca>(0);

    public Clase() {
    }

	
    public Clase(BigDecimal idClase, String descripcion) {
        this.idClase = idClase;
        this.descripcion = descripcion;
    }
    public Clase(BigDecimal idClase, String descripcion, Set<Marca> marcas) {
       this.idClase = idClase;
       this.descripcion = descripcion;
       this.marcas = marcas;
    }
   
    public BigDecimal getIdClase() {
        return this.idClase;
    }
    
    public void setIdClase(BigDecimal idClase) {
        this.idClase = idClase;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Marca> getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Set<Marca> marcas) {
        this.marcas = marcas;
    }




}


