package modelo;
// Generated 12-mar-2018 19:22:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private BigDecimal idCliente;
     private Usuario usuario;
     private String nombre;
     private String apellido;
     private String direccion;
     private String telefono;
     private Integer ci;
     private String ruc;
     private String estado;
     private Set<FacturaCabecera> facturaCabeceras = new HashSet<FacturaCabecera>(0);
     private Set<Expediente> expedientes = new HashSet<Expediente>(0);

    public Cliente() {
    }

	
    public Cliente(BigDecimal idCliente, String nombre, String apellido, String direccion, String telefono) {
        this.idCliente = idCliente;
        this.nombre = nombre;
        this.apellido = apellido;
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public Cliente(BigDecimal idCliente, Usuario usuario, String nombre, String apellido, String direccion, String telefono, Integer ci, String ruc, String estado, Set<FacturaCabecera> facturaCabeceras, Set<Expediente> expedientes) {
       this.idCliente = idCliente;
       this.usuario = usuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.telefono = telefono;
       this.ci = ci;
       this.ruc = ruc;
       this.estado = estado;
       this.facturaCabeceras = facturaCabeceras;
       this.expedientes = expedientes;
    }
   
    public BigDecimal getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(BigDecimal idCliente) {
        this.idCliente = idCliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Integer getCi() {
        return this.ci;
    }
    
    public void setCi(Integer ci) {
        this.ci = ci;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<FacturaCabecera> getFacturaCabeceras() {
        return this.facturaCabeceras;
    }
    
    public void setFacturaCabeceras(Set<FacturaCabecera> facturaCabeceras) {
        this.facturaCabeceras = facturaCabeceras;
    }
    public Set<Expediente> getExpedientes() {
        return this.expedientes;
    }
    
    public void setExpedientes(Set<Expediente> expedientes) {
        this.expedientes = expedientes;
    }




}


