package modelo;
// Generated 12-mar-2018 19:22:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Documento generated by hbm2java
 */
public class Documento  implements java.io.Serializable {


     private BigDecimal idDocumento;
     private Expediente expediente;
     private TipoDocumento tipoDocumento;
     private String descripcion;
     private Date fecha;
     private byte[] documento;

    public Documento() {
    }

    public Documento(BigDecimal idDocumento, Expediente expediente, TipoDocumento tipoDocumento, String descripcion, Date fecha, byte[] documento) {
       this.idDocumento = idDocumento;
       this.expediente = expediente;
       this.tipoDocumento = tipoDocumento;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.documento = documento;
    }
   
    public BigDecimal getIdDocumento() {
        return this.idDocumento;
    }
    
    public void setIdDocumento(BigDecimal idDocumento) {
        this.idDocumento = idDocumento;
    }
    public Expediente getExpediente() {
        return this.expediente;
    }
    
    public void setExpediente(Expediente expediente) {
        this.expediente = expediente;
    }
    public TipoDocumento getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(TipoDocumento tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public byte[] getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(byte[] documento) {
        this.documento = documento;
    }




}


