package modelo;
// Generated Apr 8, 2018 6:45:46 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Documento generated by hbm2java
 */
@Entity
@Table(name="documento"
    ,schema="public"
)
public class Documento  implements java.io.Serializable {


     private BigDecimal idDocumento;
     private Expediente expediente;
     private TipoDocumento tipoDocumento;
     private String descripcion;
     private Date fecha;
     private byte[] documento;

    public Documento() {
    }

    public Documento(BigDecimal idDocumento, Expediente expediente, TipoDocumento tipoDocumento, String descripcion, Date fecha, byte[] documento) {
       this.idDocumento = idDocumento;
       this.expediente = expediente;
       this.tipoDocumento = tipoDocumento;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.documento = documento;
    }
   
     @Id 

    
    @Column(name="id_documento", nullable=false, precision=131089, scale=0)
    public BigDecimal getIdDocumento() {
        return this.idDocumento;
    }
    
    public void setIdDocumento(BigDecimal idDocumento) {
        this.idDocumento = idDocumento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_expediente", nullable=false)
    public Expediente getExpediente() {
        return this.expediente;
    }
    
    public void setExpediente(Expediente expediente) {
        this.expediente = expediente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tipo_documento", nullable=false)
    public TipoDocumento getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(TipoDocumento tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }

    
    @Column(name="descripcion", nullable=false, length=40)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="documento", nullable=false)
    public byte[] getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(byte[] documento) {
        this.documento = documento;
    }




}


