package modelo;
// Generated Apr 7, 2018 6:38:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * EstadoMarca generated by hbm2java
 */
public class EstadoMarca  implements java.io.Serializable {


     private BigDecimal idEstado;
     private String descripcion;
     private Set marcas = new HashSet(0);

    public EstadoMarca() {
    }

	
    public EstadoMarca(BigDecimal idEstado, String descripcion) {
        this.idEstado = idEstado;
        this.descripcion = descripcion;
    }
    public EstadoMarca(BigDecimal idEstado, String descripcion, Set marcas) {
       this.idEstado = idEstado;
       this.descripcion = descripcion;
       this.marcas = marcas;
    }
   
    public BigDecimal getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(BigDecimal idEstado) {
        this.idEstado = idEstado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Set marcas) {
        this.marcas = marcas;
    }




}


