package modelo;
// Generated Apr 8, 2018 6:45:46 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoMarca generated by hbm2java
 */
@Entity
@Table(name="estado_marca"
    ,schema="public"
)
public class EstadoMarca  implements java.io.Serializable {


     private BigDecimal idEstado;
     private String descripcion;
     private Set marcas = new HashSet(0);

    public EstadoMarca() {
    }

	
    public EstadoMarca(BigDecimal idEstado, String descripcion) {
        this.idEstado = idEstado;
        this.descripcion = descripcion;
    }
    public EstadoMarca(BigDecimal idEstado, String descripcion, Set marcas) {
       this.idEstado = idEstado;
       this.descripcion = descripcion;
       this.marcas = marcas;
    }
   
     @Id 

    
    @Column(name="id_estado", nullable=false, precision=131089, scale=0)
    public BigDecimal getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(BigDecimal idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="descripcion", nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estadoMarca")
    public Set getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Set marcas) {
        this.marcas = marcas;
    }




}


