package modelo;
// Generated Apr 8, 2018 6:45:46 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Evento generated by hbm2java
 */
@Entity
@Table(name="evento"
    ,schema="public"
)
public class Evento  implements java.io.Serializable {


     private BigDecimal idEvento;
     private Marca marca;
     private String descripcion;
     private Date fecha;

    public Evento() {
    }

    public Evento(BigDecimal idEvento, Marca marca, String descripcion, Date fecha) {
       this.idEvento = idEvento;
       this.marca = marca;
       this.descripcion = descripcion;
       this.fecha = fecha;
    }
   
     @Id 

    
    @Column(name="id_evento", nullable=false, precision=131089, scale=0)
    public BigDecimal getIdEvento() {
        return this.idEvento;
    }
    
    public void setIdEvento(BigDecimal idEvento) {
        this.idEvento = idEvento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_marca", nullable=false)
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }

    
    @Column(name="descripcion", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


