package modelo;
// Generated 12-mar-2018 19:22:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private BigDecimal idEvento;
     private Marca marca;
     private String descripcion;
     private Date fecha;

    public Evento() {
    }

    public Evento(BigDecimal idEvento, Marca marca, String descripcion, Date fecha) {
       this.idEvento = idEvento;
       this.marca = marca;
       this.descripcion = descripcion;
       this.fecha = fecha;
    }
   
    public BigDecimal getIdEvento() {
        return this.idEvento;
    }
    
    public void setIdEvento(BigDecimal idEvento) {
        this.idEvento = idEvento;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


