package modelo;
// Generated Apr 7, 2018 6:38:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Expediente generated by hbm2java
 */
public class Expediente  implements java.io.Serializable {


     private BigDecimal idExpediente;
     private Abogado abogado;
     private Cliente cliente;
     private BigDecimal nroExpediente;
     private Set documentos = new HashSet(0);
     private Set marcas = new HashSet(0);

    public Expediente() {
    }

	
    public Expediente(BigDecimal idExpediente, Abogado abogado, Cliente cliente, BigDecimal nroExpediente) {
        this.idExpediente = idExpediente;
        this.abogado = abogado;
        this.cliente = cliente;
        this.nroExpediente = nroExpediente;
    }
    public Expediente(BigDecimal idExpediente, Abogado abogado, Cliente cliente, BigDecimal nroExpediente, Set documentos, Set marcas) {
       this.idExpediente = idExpediente;
       this.abogado = abogado;
       this.cliente = cliente;
       this.nroExpediente = nroExpediente;
       this.documentos = documentos;
       this.marcas = marcas;
    }
   
    public BigDecimal getIdExpediente() {
        return this.idExpediente;
    }
    
    public void setIdExpediente(BigDecimal idExpediente) {
        this.idExpediente = idExpediente;
    }
    public Abogado getAbogado() {
        return this.abogado;
    }
    
    public void setAbogado(Abogado abogado) {
        this.abogado = abogado;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public BigDecimal getNroExpediente() {
        return this.nroExpediente;
    }
    
    public void setNroExpediente(BigDecimal nroExpediente) {
        this.nroExpediente = nroExpediente;
    }
    public Set getDocumentos() {
        return this.documentos;
    }
    
    public void setDocumentos(Set documentos) {
        this.documentos = documentos;
    }
    public Set getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Set marcas) {
        this.marcas = marcas;
    }




}


