package modelo;
// Generated Apr 8, 2018 6:45:46 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Expediente generated by hbm2java
 */
@Entity
@Table(name="expediente"
    ,schema="public"
)
public class Expediente  implements java.io.Serializable {


     private BigDecimal idExpediente;
     private Abogado abogado;
     private Cliente cliente;
     private BigDecimal nroExpediente;
     private Set documentos = new HashSet(0);
     private Set marcas = new HashSet(0);

    public Expediente() {
    }

	
    public Expediente(BigDecimal idExpediente, Abogado abogado, Cliente cliente, BigDecimal nroExpediente) {
        this.idExpediente = idExpediente;
        this.abogado = abogado;
        this.cliente = cliente;
        this.nroExpediente = nroExpediente;
    }
    public Expediente(BigDecimal idExpediente, Abogado abogado, Cliente cliente, BigDecimal nroExpediente, Set documentos, Set marcas) {
       this.idExpediente = idExpediente;
       this.abogado = abogado;
       this.cliente = cliente;
       this.nroExpediente = nroExpediente;
       this.documentos = documentos;
       this.marcas = marcas;
    }
   
     @Id 

    
    @Column(name="id_expediente", nullable=false, precision=131089, scale=0)
    public BigDecimal getIdExpediente() {
        return this.idExpediente;
    }
    
    public void setIdExpediente(BigDecimal idExpediente) {
        this.idExpediente = idExpediente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_abogado", nullable=false)
    public Abogado getAbogado() {
        return this.abogado;
    }
    
    public void setAbogado(Abogado abogado) {
        this.abogado = abogado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    
    @Column(name="nro_expediente", nullable=false, precision=131089, scale=0)
    public BigDecimal getNroExpediente() {
        return this.nroExpediente;
    }
    
    public void setNroExpediente(BigDecimal nroExpediente) {
        this.nroExpediente = nroExpediente;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="expediente")
    public Set getDocumentos() {
        return this.documentos;
    }
    
    public void setDocumentos(Set documentos) {
        this.documentos = documentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="expediente")
    public Set getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Set marcas) {
        this.marcas = marcas;
    }




}


