package modelo;
// Generated Apr 8, 2018 6:45:46 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FacturaCabecera generated by hbm2java
 */
@Entity
@Table(name="factura_cabecera"
    ,schema="public"
)
public class FacturaCabecera  implements java.io.Serializable {


     private BigDecimal idFactCab;
     private Cliente cliente;
     private long numFact;
     private Date fecha;
     private BigDecimal montoTotal;
     private char tipo;
     private char formaPago;
     private BigDecimal iva;
     private Set planPagos = new HashSet(0);
     private Set facturaDetalles = new HashSet(0);

    public FacturaCabecera() {
    }

	
    public FacturaCabecera(BigDecimal idFactCab, Cliente cliente, long numFact, Date fecha, BigDecimal montoTotal, char tipo, char formaPago, BigDecimal iva) {
        this.idFactCab = idFactCab;
        this.cliente = cliente;
        this.numFact = numFact;
        this.fecha = fecha;
        this.montoTotal = montoTotal;
        this.tipo = tipo;
        this.formaPago = formaPago;
        this.iva = iva;
    }
    public FacturaCabecera(BigDecimal idFactCab, Cliente cliente, long numFact, Date fecha, BigDecimal montoTotal, char tipo, char formaPago, BigDecimal iva, Set planPagos, Set facturaDetalles) {
       this.idFactCab = idFactCab;
       this.cliente = cliente;
       this.numFact = numFact;
       this.fecha = fecha;
       this.montoTotal = montoTotal;
       this.tipo = tipo;
       this.formaPago = formaPago;
       this.iva = iva;
       this.planPagos = planPagos;
       this.facturaDetalles = facturaDetalles;
    }
   
     @Id 

    
    @Column(name="id_fact_cab", nullable=false, precision=131089, scale=0)
    public BigDecimal getIdFactCab() {
        return this.idFactCab;
    }
    
    public void setIdFactCab(BigDecimal idFactCab) {
        this.idFactCab = idFactCab;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    
    @Column(name="num_fact", nullable=false, precision=13, scale=0)
    public long getNumFact() {
        return this.numFact;
    }
    
    public void setNumFact(long numFact) {
        this.numFact = numFact;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="monto_total", nullable=false, precision=131089, scale=0)
    public BigDecimal getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(BigDecimal montoTotal) {
        this.montoTotal = montoTotal;
    }

    
    @Column(name="tipo", nullable=false, length=1)
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="forma_pago", nullable=false, length=1)
    public char getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(char formaPago) {
        this.formaPago = formaPago;
    }

    
    @Column(name="iva", nullable=false, precision=131089, scale=0)
    public BigDecimal getIva() {
        return this.iva;
    }
    
    public void setIva(BigDecimal iva) {
        this.iva = iva;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="facturaCabecera")
    public Set getPlanPagos() {
        return this.planPagos;
    }
    
    public void setPlanPagos(Set planPagos) {
        this.planPagos = planPagos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="facturaCabecera")
    public Set getFacturaDetalles() {
        return this.facturaDetalles;
    }
    
    public void setFacturaDetalles(Set facturaDetalles) {
        this.facturaDetalles = facturaDetalles;
    }




}


