package modelo;
// Generated 12-mar-2018 19:22:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FacturaCabecera generated by hbm2java
 */
public class FacturaCabecera  implements java.io.Serializable {


     private BigDecimal idFactCab;
     private Cliente cliente;
     private long numFact;
     private Date fecha;
     private BigDecimal montoTotal;
     private char tipo;
     private char formaPago;
     private BigDecimal iva;
     private Set<PlanPago> planPagos = new HashSet<PlanPago>(0);
     private Set<FacturaDetalle> facturaDetalles = new HashSet<FacturaDetalle>(0);

    public FacturaCabecera() {
    }

	
    public FacturaCabecera(BigDecimal idFactCab, Cliente cliente, long numFact, Date fecha, BigDecimal montoTotal, char tipo, char formaPago, BigDecimal iva) {
        this.idFactCab = idFactCab;
        this.cliente = cliente;
        this.numFact = numFact;
        this.fecha = fecha;
        this.montoTotal = montoTotal;
        this.tipo = tipo;
        this.formaPago = formaPago;
        this.iva = iva;
    }
    public FacturaCabecera(BigDecimal idFactCab, Cliente cliente, long numFact, Date fecha, BigDecimal montoTotal, char tipo, char formaPago, BigDecimal iva, Set<PlanPago> planPagos, Set<FacturaDetalle> facturaDetalles) {
       this.idFactCab = idFactCab;
       this.cliente = cliente;
       this.numFact = numFact;
       this.fecha = fecha;
       this.montoTotal = montoTotal;
       this.tipo = tipo;
       this.formaPago = formaPago;
       this.iva = iva;
       this.planPagos = planPagos;
       this.facturaDetalles = facturaDetalles;
    }
   
    public BigDecimal getIdFactCab() {
        return this.idFactCab;
    }
    
    public void setIdFactCab(BigDecimal idFactCab) {
        this.idFactCab = idFactCab;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public long getNumFact() {
        return this.numFact;
    }
    
    public void setNumFact(long numFact) {
        this.numFact = numFact;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(BigDecimal montoTotal) {
        this.montoTotal = montoTotal;
    }
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }
    public char getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(char formaPago) {
        this.formaPago = formaPago;
    }
    public BigDecimal getIva() {
        return this.iva;
    }
    
    public void setIva(BigDecimal iva) {
        this.iva = iva;
    }
    public Set<PlanPago> getPlanPagos() {
        return this.planPagos;
    }
    
    public void setPlanPagos(Set<PlanPago> planPagos) {
        this.planPagos = planPagos;
    }
    public Set<FacturaDetalle> getFacturaDetalles() {
        return this.facturaDetalles;
    }
    
    public void setFacturaDetalles(Set<FacturaDetalle> facturaDetalles) {
        this.facturaDetalles = facturaDetalles;
    }




}


