package modelo;
// Generated Apr 8, 2018 6:45:46 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FacturaDetalle generated by hbm2java
 */
@Entity
@Table(name="factura_detalle"
    ,schema="public"
)
public class FacturaDetalle  implements java.io.Serializable {


     private BigDecimal idFactDet;
     private FacturaCabecera facturaCabecera;
     private Tramite tramite;
     private BigDecimal numeroItem;
     private BigDecimal precio;
     private String descripcion;
     private BigDecimal iva;

    public FacturaDetalle() {
    }

    public FacturaDetalle(BigDecimal idFactDet, FacturaCabecera facturaCabecera, Tramite tramite, BigDecimal numeroItem, BigDecimal precio, String descripcion, BigDecimal iva) {
       this.idFactDet = idFactDet;
       this.facturaCabecera = facturaCabecera;
       this.tramite = tramite;
       this.numeroItem = numeroItem;
       this.precio = precio;
       this.descripcion = descripcion;
       this.iva = iva;
    }
   
     @Id 

    
    @Column(name="id_fact_det", nullable=false, precision=131089, scale=0)
    public BigDecimal getIdFactDet() {
        return this.idFactDet;
    }
    
    public void setIdFactDet(BigDecimal idFactDet) {
        this.idFactDet = idFactDet;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_fact_cabecera", nullable=false)
    public FacturaCabecera getFacturaCabecera() {
        return this.facturaCabecera;
    }
    
    public void setFacturaCabecera(FacturaCabecera facturaCabecera) {
        this.facturaCabecera = facturaCabecera;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tramite", nullable=false)
    public Tramite getTramite() {
        return this.tramite;
    }
    
    public void setTramite(Tramite tramite) {
        this.tramite = tramite;
    }

    
    @Column(name="numero_item", nullable=false, precision=131089, scale=0)
    public BigDecimal getNumeroItem() {
        return this.numeroItem;
    }
    
    public void setNumeroItem(BigDecimal numeroItem) {
        this.numeroItem = numeroItem;
    }

    
    @Column(name="precio", nullable=false, precision=131089, scale=0)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

    
    @Column(name="descripcion", nullable=false, length=40)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="iva", nullable=false, precision=131089, scale=0)
    public BigDecimal getIva() {
        return this.iva;
    }
    
    public void setIva(BigDecimal iva) {
        this.iva = iva;
    }




}


