package modelo;
// Generated Apr 7, 2018 6:38:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * FacturaDetalle generated by hbm2java
 */
public class FacturaDetalle  implements java.io.Serializable {


     private BigDecimal idFactDet;
     private FacturaCabecera facturaCabecera;
     private Tramite tramite;
     private BigDecimal numeroItem;
     private BigDecimal precio;
     private String descripcion;
     private BigDecimal iva;

    public FacturaDetalle() {
    }

    public FacturaDetalle(BigDecimal idFactDet, FacturaCabecera facturaCabecera, Tramite tramite, BigDecimal numeroItem, BigDecimal precio, String descripcion, BigDecimal iva) {
       this.idFactDet = idFactDet;
       this.facturaCabecera = facturaCabecera;
       this.tramite = tramite;
       this.numeroItem = numeroItem;
       this.precio = precio;
       this.descripcion = descripcion;
       this.iva = iva;
    }
   
    public BigDecimal getIdFactDet() {
        return this.idFactDet;
    }
    
    public void setIdFactDet(BigDecimal idFactDet) {
        this.idFactDet = idFactDet;
    }
    public FacturaCabecera getFacturaCabecera() {
        return this.facturaCabecera;
    }
    
    public void setFacturaCabecera(FacturaCabecera facturaCabecera) {
        this.facturaCabecera = facturaCabecera;
    }
    public Tramite getTramite() {
        return this.tramite;
    }
    
    public void setTramite(Tramite tramite) {
        this.tramite = tramite;
    }
    public BigDecimal getNumeroItem() {
        return this.numeroItem;
    }
    
    public void setNumeroItem(BigDecimal numeroItem) {
        this.numeroItem = numeroItem;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getIva() {
        return this.iva;
    }
    
    public void setIva(BigDecimal iva) {
        this.iva = iva;
    }




}


