package modelo;
// Generated Apr 8, 2018 6:45:46 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Historial generated by hbm2java
 */
@Entity
@Table(name="historial"
    ,schema="public"
)
public class Historial  implements java.io.Serializable {


     private BigDecimal idHistorial;
     private Abogado abogado;
     private BigDecimal idMarca;
     private Date fecha;
     private String operacion;
     private String detalle;

    public Historial() {
    }

    public Historial(BigDecimal idHistorial, Abogado abogado, BigDecimal idMarca, Date fecha, String operacion, String detalle) {
       this.idHistorial = idHistorial;
       this.abogado = abogado;
       this.idMarca = idMarca;
       this.fecha = fecha;
       this.operacion = operacion;
       this.detalle = detalle;
    }
   
     @Id 

    
    @Column(name="id_historial", nullable=false, precision=131089, scale=0)
    public BigDecimal getIdHistorial() {
        return this.idHistorial;
    }
    
    public void setIdHistorial(BigDecimal idHistorial) {
        this.idHistorial = idHistorial;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_abogado", nullable=false)
    public Abogado getAbogado() {
        return this.abogado;
    }
    
    public void setAbogado(Abogado abogado) {
        this.abogado = abogado;
    }

    
    @Column(name="id_marca", nullable=false, precision=131089, scale=0)
    public BigDecimal getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(BigDecimal idMarca) {
        this.idMarca = idMarca;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="operacion", nullable=false)
    public String getOperacion() {
        return this.operacion;
    }
    
    public void setOperacion(String operacion) {
        this.operacion = operacion;
    }

    
    @Column(name="detalle", nullable=false)
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }




}


