package modelo;
// Generated Apr 7, 2018 6:38:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private BigDecimal idMarca;
     private Clase clase;
     private EstadoMarca estadoMarca;
     private Expediente expediente;
     private Pais pais;
     private TipoMarca tipoMarca;
     private String producto;
     private String titular;
     private Date fechaPresentacion;
     private Date fechaPublicacion;
     private Date concesion;
     private Date vencimiento;
     private String observacion;
     private byte[] imagenMarca;
     private Set eventos = new HashSet(0);

    public Marca() {
    }

	
    public Marca(BigDecimal idMarca, Clase clase, EstadoMarca estadoMarca, Expediente expediente, Pais pais, TipoMarca tipoMarca, String producto, String titular) {
        this.idMarca = idMarca;
        this.clase = clase;
        this.estadoMarca = estadoMarca;
        this.expediente = expediente;
        this.pais = pais;
        this.tipoMarca = tipoMarca;
        this.producto = producto;
        this.titular = titular;
    }
    public Marca(BigDecimal idMarca, Clase clase, EstadoMarca estadoMarca, Expediente expediente, Pais pais, TipoMarca tipoMarca, String producto, String titular, Date fechaPresentacion, Date fechaPublicacion, Date concesion, Date vencimiento, String observacion, byte[] imagenMarca, Set eventos) {
       this.idMarca = idMarca;
       this.clase = clase;
       this.estadoMarca = estadoMarca;
       this.expediente = expediente;
       this.pais = pais;
       this.tipoMarca = tipoMarca;
       this.producto = producto;
       this.titular = titular;
       this.fechaPresentacion = fechaPresentacion;
       this.fechaPublicacion = fechaPublicacion;
       this.concesion = concesion;
       this.vencimiento = vencimiento;
       this.observacion = observacion;
       this.imagenMarca = imagenMarca;
       this.eventos = eventos;
    }
   
    public BigDecimal getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(BigDecimal idMarca) {
        this.idMarca = idMarca;
    }
    public Clase getClase() {
        return this.clase;
    }
    
    public void setClase(Clase clase) {
        this.clase = clase;
    }
    public EstadoMarca getEstadoMarca() {
        return this.estadoMarca;
    }
    
    public void setEstadoMarca(EstadoMarca estadoMarca) {
        this.estadoMarca = estadoMarca;
    }
    public Expediente getExpediente() {
        return this.expediente;
    }
    
    public void setExpediente(Expediente expediente) {
        this.expediente = expediente;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public TipoMarca getTipoMarca() {
        return this.tipoMarca;
    }
    
    public void setTipoMarca(TipoMarca tipoMarca) {
        this.tipoMarca = tipoMarca;
    }
    public String getProducto() {
        return this.producto;
    }
    
    public void setProducto(String producto) {
        this.producto = producto;
    }
    public String getTitular() {
        return this.titular;
    }
    
    public void setTitular(String titular) {
        this.titular = titular;
    }
    public Date getFechaPresentacion() {
        return this.fechaPresentacion;
    }
    
    public void setFechaPresentacion(Date fechaPresentacion) {
        this.fechaPresentacion = fechaPresentacion;
    }
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }
    public Date getConcesion() {
        return this.concesion;
    }
    
    public void setConcesion(Date concesion) {
        this.concesion = concesion;
    }
    public Date getVencimiento() {
        return this.vencimiento;
    }
    
    public void setVencimiento(Date vencimiento) {
        this.vencimiento = vencimiento;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public byte[] getImagenMarca() {
        return this.imagenMarca;
    }
    
    public void setImagenMarca(byte[] imagenMarca) {
        this.imagenMarca = imagenMarca;
    }
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }




}


