package modelo;
// Generated 12-mar-2018 19:22:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private BigDecimal idPais;
     private String pais;
     private Set<Marca> marcas = new HashSet<Marca>(0);

    public Pais() {
    }

	
    public Pais(BigDecimal idPais, String pais) {
        this.idPais = idPais;
        this.pais = pais;
    }
    public Pais(BigDecimal idPais, String pais, Set<Marca> marcas) {
       this.idPais = idPais;
       this.pais = pais;
       this.marcas = marcas;
    }
   
    public BigDecimal getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(BigDecimal idPais) {
        this.idPais = idPais;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Set<Marca> getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Set<Marca> marcas) {
        this.marcas = marcas;
    }




}


