package modelo;
// Generated 12-mar-2018 19:22:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * PlanPago generated by hbm2java
 */
public class PlanPago  implements java.io.Serializable {


     private BigDecimal nombreCuenta;
     private FacturaCabecera facturaCabecera;
     private BigDecimal monto;
     private Date vencimiento;
     private Date fechaPago;

    public PlanPago() {
    }

    public PlanPago(BigDecimal nombreCuenta, FacturaCabecera facturaCabecera, BigDecimal monto, Date vencimiento, Date fechaPago) {
       this.nombreCuenta = nombreCuenta;
       this.facturaCabecera = facturaCabecera;
       this.monto = monto;
       this.vencimiento = vencimiento;
       this.fechaPago = fechaPago;
    }
   
    public BigDecimal getNombreCuenta() {
        return this.nombreCuenta;
    }
    
    public void setNombreCuenta(BigDecimal nombreCuenta) {
        this.nombreCuenta = nombreCuenta;
    }
    public FacturaCabecera getFacturaCabecera() {
        return this.facturaCabecera;
    }
    
    public void setFacturaCabecera(FacturaCabecera facturaCabecera) {
        this.facturaCabecera = facturaCabecera;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public Date getVencimiento() {
        return this.vencimiento;
    }
    
    public void setVencimiento(Date vencimiento) {
        this.vencimiento = vencimiento;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }




}


