package modelo;
// Generated Apr 8, 2018 6:45:46 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoMarca generated by hbm2java
 */
@Entity
@Table(name="tipo_marca"
    ,schema="public"
)
public class TipoMarca  implements java.io.Serializable {


     private BigDecimal idTipoMarca;
     private String descripcion;
     private Set marcas = new HashSet(0);

    public TipoMarca() {
    }

	
    public TipoMarca(BigDecimal idTipoMarca, String descripcion) {
        this.idTipoMarca = idTipoMarca;
        this.descripcion = descripcion;
    }
    public TipoMarca(BigDecimal idTipoMarca, String descripcion, Set marcas) {
       this.idTipoMarca = idTipoMarca;
       this.descripcion = descripcion;
       this.marcas = marcas;
    }
   
     @Id 

    
    @Column(name="id_tipo_marca", nullable=false, precision=131089, scale=0)
    public BigDecimal getIdTipoMarca() {
        return this.idTipoMarca;
    }
    
    public void setIdTipoMarca(BigDecimal idTipoMarca) {
        this.idTipoMarca = idTipoMarca;
    }

    
    @Column(name="descripcion", nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoMarca")
    public Set getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Set marcas) {
        this.marcas = marcas;
    }




}


