package modelo;
// Generated 12-mar-2018 19:22:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoMarca generated by hbm2java
 */
public class TipoMarca  implements java.io.Serializable {


     private BigDecimal idTipoMarca;
     private String descripcion;
     private Set<Marca> marcas = new HashSet<Marca>(0);

    public TipoMarca() {
    }

	
    public TipoMarca(BigDecimal idTipoMarca, String descripcion) {
        this.idTipoMarca = idTipoMarca;
        this.descripcion = descripcion;
    }
    public TipoMarca(BigDecimal idTipoMarca, String descripcion, Set<Marca> marcas) {
       this.idTipoMarca = idTipoMarca;
       this.descripcion = descripcion;
       this.marcas = marcas;
    }
   
    public BigDecimal getIdTipoMarca() {
        return this.idTipoMarca;
    }
    
    public void setIdTipoMarca(BigDecimal idTipoMarca) {
        this.idTipoMarca = idTipoMarca;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Marca> getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Set<Marca> marcas) {
        this.marcas = marcas;
    }




}


