package modelo;
// Generated Apr 8, 2018 6:45:46 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoDocumento generated by hbm2java
 */
@Entity
@Table(name="tipo_documento"
    ,schema="public"
)
public class TipoDocumento  implements java.io.Serializable {


     private BigDecimal idTipoDocumento;
     private String descripcion;
     private Set documentos = new HashSet(0);

    public TipoDocumento() {
    }

	
    public TipoDocumento(BigDecimal idTipoDocumento, String descripcion) {
        this.idTipoDocumento = idTipoDocumento;
        this.descripcion = descripcion;
    }
    public TipoDocumento(BigDecimal idTipoDocumento, String descripcion, Set documentos) {
       this.idTipoDocumento = idTipoDocumento;
       this.descripcion = descripcion;
       this.documentos = documentos;
    }
   
     @Id 

    
    @Column(name="id_tipo_documento", nullable=false, precision=131089, scale=0)
    public BigDecimal getIdTipoDocumento() {
        return this.idTipoDocumento;
    }
    
    public void setIdTipoDocumento(BigDecimal idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }

    
    @Column(name="descripcion", nullable=false, length=40)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoDocumento")
    public Set getDocumentos() {
        return this.documentos;
    }
    
    public void setDocumentos(Set documentos) {
        this.documentos = documentos;
    }




}


