package modelo;
// Generated Apr 7, 2018 6:38:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoMarca generated by hbm2java
 */
public class TipoMarca  implements java.io.Serializable {


     private BigDecimal idTipoMarca;
     private String descripcion;
     private Set marcas = new HashSet(0);

    public TipoMarca() {
    }

	
    public TipoMarca(BigDecimal idTipoMarca, String descripcion) {
        this.idTipoMarca = idTipoMarca;
        this.descripcion = descripcion;
    }
    public TipoMarca(BigDecimal idTipoMarca, String descripcion, Set marcas) {
       this.idTipoMarca = idTipoMarca;
       this.descripcion = descripcion;
       this.marcas = marcas;
    }
   
    public BigDecimal getIdTipoMarca() {
        return this.idTipoMarca;
    }
    
    public void setIdTipoMarca(BigDecimal idTipoMarca) {
        this.idTipoMarca = idTipoMarca;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Set marcas) {
        this.marcas = marcas;
    }




}


