package modelo;
// Generated Apr 7, 2018 6:38:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocumento generated by hbm2java
 */
public class TipoDocumento  implements java.io.Serializable {


     private BigDecimal idTipoDocumento;
     private String descripcion;
     private Set documentos = new HashSet(0);

    public TipoDocumento() {
    }

	
    public TipoDocumento(BigDecimal idTipoDocumento, String descripcion) {
        this.idTipoDocumento = idTipoDocumento;
        this.descripcion = descripcion;
    }
    public TipoDocumento(BigDecimal idTipoDocumento, String descripcion, Set documentos) {
       this.idTipoDocumento = idTipoDocumento;
       this.descripcion = descripcion;
       this.documentos = documentos;
    }
   
    public BigDecimal getIdTipoDocumento() {
        return this.idTipoDocumento;
    }
    
    public void setIdTipoDocumento(BigDecimal idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getDocumentos() {
        return this.documentos;
    }
    
    public void setDocumentos(Set documentos) {
        this.documentos = documentos;
    }




}


