package modelo;
// Generated 12-mar-2018 19:22:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tramite generated by hbm2java
 */
public class Tramite  implements java.io.Serializable {


     private BigDecimal idTramite;
     private BigDecimal precio;
     private String nombre;
     private Set<FacturaDetalle> facturaDetalles = new HashSet<FacturaDetalle>(0);

    public Tramite() {
    }

	
    public Tramite(BigDecimal idTramite, BigDecimal precio, String nombre) {
        this.idTramite = idTramite;
        this.precio = precio;
        this.nombre = nombre;
    }
    public Tramite(BigDecimal idTramite, BigDecimal precio, String nombre, Set<FacturaDetalle> facturaDetalles) {
       this.idTramite = idTramite;
       this.precio = precio;
       this.nombre = nombre;
       this.facturaDetalles = facturaDetalles;
    }
   
    public BigDecimal getIdTramite() {
        return this.idTramite;
    }
    
    public void setIdTramite(BigDecimal idTramite) {
        this.idTramite = idTramite;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<FacturaDetalle> getFacturaDetalles() {
        return this.facturaDetalles;
    }
    
    public void setFacturaDetalles(Set<FacturaDetalle> facturaDetalles) {
        this.facturaDetalles = facturaDetalles;
    }




}


