package modelo;
// Generated Apr 8, 2018 6:45:46 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tramite generated by hbm2java
 */
@Entity
@Table(name="tramite"
    ,schema="public"
)
public class Tramite  implements java.io.Serializable {


     private BigDecimal idTramite;
     private BigDecimal precio;
     private String nombre;
     private Set facturaDetalles = new HashSet(0);

    public Tramite() {
    }

	
    public Tramite(BigDecimal idTramite, BigDecimal precio, String nombre) {
        this.idTramite = idTramite;
        this.precio = precio;
        this.nombre = nombre;
    }
    public Tramite(BigDecimal idTramite, BigDecimal precio, String nombre, Set facturaDetalles) {
       this.idTramite = idTramite;
       this.precio = precio;
       this.nombre = nombre;
       this.facturaDetalles = facturaDetalles;
    }
   
     @Id 

    
    @Column(name="id_tramite", nullable=false, precision=131089, scale=0)
    public BigDecimal getIdTramite() {
        return this.idTramite;
    }
    
    public void setIdTramite(BigDecimal idTramite) {
        this.idTramite = idTramite;
    }

    
    @Column(name="precio", nullable=false, precision=131089, scale=0)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

    
    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tramite")
    public Set getFacturaDetalles() {
        return this.facturaDetalles;
    }
    
    public void setFacturaDetalles(Set facturaDetalles) {
        this.facturaDetalles = facturaDetalles;
    }




}


