package modelo;
// Generated 12-mar-2018 19:22:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private BigDecimal idUsuario;
     private Rol rol;
     private String cuenta;
     private String password;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);
     private Set<Abogado> abogados = new HashSet<Abogado>(0);

    public Usuario() {
    }

	
    public Usuario(BigDecimal idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuario(BigDecimal idUsuario, Rol rol, String cuenta, String password, Set<Cliente> clientes, Set<Abogado> abogados) {
       this.idUsuario = idUsuario;
       this.rol = rol;
       this.cuenta = cuenta;
       this.password = password;
       this.clientes = clientes;
       this.abogados = abogados;
    }
   
    public BigDecimal getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(BigDecimal idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }
    public Set<Abogado> getAbogados() {
        return this.abogados;
    }
    
    public void setAbogados(Set<Abogado> abogados) {
        this.abogados = abogados;
    }




}


