package modelo;
// Generated Apr 8, 2018 6:45:46 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     private BigDecimal idUsuario;
     private Rol rol;
     private String cuenta;
     private String password;
     private Set clientes = new HashSet(0);
     private Set abogados = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(BigDecimal idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuario(BigDecimal idUsuario, Rol rol, String cuenta, String password, Set clientes, Set abogados) {
       this.idUsuario = idUsuario;
       this.rol = rol;
       this.cuenta = cuenta;
       this.password = password;
       this.clientes = clientes;
       this.abogados = abogados;
    }
   
     @Id 

    
    @Column(name="id_usuario", nullable=false, precision=131089, scale=0)
    public BigDecimal getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(BigDecimal idUsuario) {
        this.idUsuario = idUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_rol")
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }

    
    @Column(name="cuenta", length=10)
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }

    
    @Column(name="password", length=15)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getAbogados() {
        return this.abogados;
    }
    
    public void setAbogados(Set abogados) {
        this.abogados = abogados;
    }




}


